project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 ML Fundamentals"
            file: content/01_journal/01_ml_fundamentals.qmd
          - text: "02 Supervised ML Regression"
            file: content/01_journal/02_supervised_ml_regression.qmd
          - text: "03 Automated ML (I)"
            file: content/01_journal/03_automated_ml_h20_1.qmd
          - text: "04 Automated ML (II)"
            file: content/01_journal/04_automated_ml_h20_2.qmd
          - text: "05 Performance Measures"
            file: content/01_journal/05_performance_measures.qmd
          - text: "06 Black-Box Models"
            file: content/01_journal/06_black_box_models.qmd
format:
  html:
    df-print: paged
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
output: 
    html_document:
        df_print: paged
filters:
   - lightbox
lightbox: auto